"""initial schema + lookups seed

Revision ID: 0acdc0b0004a
Revises: 
Create Date: 2026-06-06 18:36:47.682213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acdc0b0004a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('security_type_id', sa.Integer(), nullable=False),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('payouts_per_year', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['security_type_id'], ['security_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('month_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month_id', name='uq_month_settings_year_month')
    )
    op.create_table('monthly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    _seed_lookups()


def _seed_lookups() -> None:
    """Наполнить справочники стартовыми значениями."""
    months = [
        "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь",
        "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь",
    ]
    op.bulk_insert(
        sa.table(
            "months",
            sa.column("name", sa.String),
            sa.column("order_index", sa.Integer),
        ),
        [{"name": name, "order_index": i} for i, name in enumerate(months, start=1)],
    )

    op.bulk_insert(
        sa.table("security_types", sa.column("name", sa.String)),
        [{"name": n} for n in ["Вклад", "Облигация"]],
    )

    op.bulk_insert(
        sa.table("asset_types", sa.column("name", sa.String)),
        [
            {"name": n}
            for n in [
                "Наличные", "Карта", "Вклад",
                "Облигации", "Брокерский счёт", "Другое",
            ]
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_plans')
    op.drop_table('month_settings')
    op.drop_table('investments')
    op.drop_table('assets')
    op.drop_table('security_types')
    op.drop_table('operations')
    op.drop_table('months')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
